# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rename_photos.ui'
#
# Created: Sun Dec  8 11:53:10 2013
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog_rename_files(object):
    def setupUi(self, Dialog_rename_files):
        Dialog_rename_files.setObjectName("Dialog_rename_files")
        Dialog_rename_files.resize(783, 626)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog_rename_files)
        self.buttonBox.setGeometry(QtCore.QRect(440, 590, 331, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtGui.QLabel(Dialog_rename_files)
        self.label.setGeometry(QtCore.QRect(10, 10, 721, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label_5 = QtGui.QLabel(Dialog_rename_files)
        self.label_5.setGeometry(QtCore.QRect(70, 580, 441, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setItalic(True)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget = QtGui.QTabWidget(Dialog_rename_files)
        self.tabWidget.setGeometry(QtCore.QRect(10, 130, 761, 451))
        self.tabWidget.setObjectName("tabWidget")
        self.simple = QtGui.QWidget()
        self.simple.setObjectName("simple")
        self.frame = QtGui.QFrame(self.simple)
        self.frame.setGeometry(QtCore.QRect(460, 270, 221, 141))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 151, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtGui.QWidget(self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_fileext_asis = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_fileext_asis.setChecked(True)
        self.radioButton_fileext_asis.setObjectName("radioButton_fileext_asis")
        self.verticalLayout.addWidget(self.radioButton_fileext_asis)
        self.radioButton_fileext_tolower = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_fileext_tolower.setObjectName("radioButton_fileext_tolower")
        self.verticalLayout.addWidget(self.radioButton_fileext_tolower)
        self.radioButton_fileext_toupper = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_fileext_toupper.setObjectName("radioButton_fileext_toupper")
        self.verticalLayout.addWidget(self.radioButton_fileext_toupper)
        self.label_3 = QtGui.QLabel(self.simple)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 281, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.frame_6 = QtGui.QFrame(self.simple)
        self.frame_6.setGeometry(QtCore.QRect(10, 270, 421, 121))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setLineWidth(2)
        self.frame_6.setObjectName("frame_6")
        self.label_12 = QtGui.QLabel(self.frame_6)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 381, 51))
        self.label_12.setWordWrap(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.frame_6)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 60, 391, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtGui.QLabel(self.horizontalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.comboBox_digits = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_digits.setObjectName("comboBox_digits")
        self.comboBox_digits.addItem("")
        self.comboBox_digits.addItem("")
        self.comboBox_digits.addItem("")
        self.comboBox_digits.addItem("")
        self.comboBox_digits.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_digits)
        self.comboBox_startcount = QtGui.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_startcount.setObjectName("comboBox_startcount")
        self.comboBox_startcount.addItem("")
        self.comboBox_startcount.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_startcount)
        self.frame_4 = QtGui.QFrame(self.simple)
        self.frame_4.setGeometry(QtCore.QRect(370, 10, 371, 231))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setLineWidth(2)
        self.frame_4.setObjectName("frame_4")
        self.gridLayoutWidget_2 = QtGui.QWidget(self.frame_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 342, 213))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.suffix_string = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.suffix_string.setObjectName("suffix_string")
        self.gridLayout_2.addWidget(self.suffix_string, 2, 2, 1, 1)
        self.radioButton_suffix_datetime = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_suffix_datetime.setChecked(False)
        self.radioButton_suffix_datetime.setObjectName("radioButton_suffix_datetime")
        self.gridLayout_2.addWidget(self.radioButton_suffix_datetime, 3, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.radioButton_suffix_string = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_suffix_string.setChecked(False)
        self.radioButton_suffix_string.setObjectName("radioButton_suffix_string")
        self.gridLayout_2.addWidget(self.radioButton_suffix_string, 2, 0, 1, 1)
        self.comboBox_suffix_datetime = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_suffix_datetime.setObjectName("comboBox_suffix_datetime")
        self.comboBox_suffix_datetime.addItem("")
        self.comboBox_suffix_datetime.addItem("")
        self.comboBox_suffix_datetime.addItem("")
        self.comboBox_suffix_datetime.addItem("")
        self.comboBox_suffix_datetime.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_suffix_datetime, 3, 2, 1, 1)
        self.comboBox_suffix_date = QtGui.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_suffix_date.setObjectName("comboBox_suffix_date")
        self.comboBox_suffix_date.addItem("")
        self.comboBox_suffix_date.addItem("")
        self.comboBox_suffix_date.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_suffix_date, 4, 2, 1, 1)
        self.radioButton_suffix_date = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_suffix_date.setObjectName("radioButton_suffix_date")
        self.gridLayout_2.addWidget(self.radioButton_suffix_date, 4, 0, 1, 1)
        self.radioButton_suffix_donotuse = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_suffix_donotuse.setChecked(True)
        self.radioButton_suffix_donotuse.setObjectName("radioButton_suffix_donotuse")
        self.gridLayout_2.addWidget(self.radioButton_suffix_donotuse, 1, 0, 1, 1)
        self.radioButton_model = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_model.setObjectName("radioButton_model")
        self.gridLayout_2.addWidget(self.radioButton_model, 5, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 5, 2, 1, 1)
        self.radioButton_orgfilename = QtGui.QRadioButton(self.gridLayoutWidget_2)
        self.radioButton_orgfilename.setObjectName("radioButton_orgfilename")
        self.gridLayout_2.addWidget(self.radioButton_orgfilename, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 6, 2, 1, 1)
        self.frame_3 = QtGui.QFrame(self.simple)
        self.frame_3.setGeometry(QtCore.QRect(10, 30, 321, 141))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.frame_3.setObjectName("frame_3")
        self.gridLayoutWidget = QtGui.QWidget(self.frame_3)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 0, 303, 132))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.comboBox_prefix_date = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_prefix_date.setObjectName("comboBox_prefix_date")
        self.comboBox_prefix_date.addItem("")
        self.comboBox_prefix_date.addItem("")
        self.comboBox_prefix_date.addItem("")
        self.gridLayout.addWidget(self.comboBox_prefix_date, 2, 1, 1, 1)
        self.radioButton_prefix_datetime = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_prefix_datetime.setChecked(True)
        self.radioButton_prefix_datetime.setObjectName("radioButton_prefix_datetime")
        self.gridLayout.addWidget(self.radioButton_prefix_datetime, 1, 0, 1, 1)
        self.radioButton_prefix_date = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_prefix_date.setObjectName("radioButton_prefix_date")
        self.gridLayout.addWidget(self.radioButton_prefix_date, 2, 0, 1, 1)
        self.comboBox_prefix_datetime = QtGui.QComboBox(self.gridLayoutWidget)
        self.comboBox_prefix_datetime.setObjectName("comboBox_prefix_datetime")
        self.comboBox_prefix_datetime.addItem("")
        self.comboBox_prefix_datetime.addItem("")
        self.comboBox_prefix_datetime.addItem("")
        self.comboBox_prefix_datetime.addItem("")
        self.comboBox_prefix_datetime.addItem("")
        self.gridLayout.addWidget(self.comboBox_prefix_datetime, 1, 1, 1, 1)
        self.radioButton_prefix_string = QtGui.QRadioButton(self.gridLayoutWidget)
        self.radioButton_prefix_string.setObjectName("radioButton_prefix_string")
        self.gridLayout.addWidget(self.radioButton_prefix_string, 3, 0, 1, 1)
        self.prefix_string = QtGui.QLineEdit(self.gridLayoutWidget)
        self.prefix_string.setObjectName("prefix_string")
        self.gridLayout.addWidget(self.prefix_string, 3, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.simple)
        self.label_20.setGeometry(QtCore.QRect(10, 180, 321, 61))
        self.label_20.setWordWrap(True)
        self.label_20.setObjectName("label_20")
        self.tabWidget.addTab(self.simple, "")
        self.doityourself = QtGui.QWidget()
        self.doityourself.setObjectName("doityourself")
        self.gridLayoutWidget_3 = QtGui.QWidget(self.doityourself)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 721, 311))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(10, 10, -1, -1)
        self.gridLayout_3.setHorizontalSpacing(50)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 6, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 7, 0, 1, 1)
        self.s01 = QtGui.QLineEdit(self.gridLayoutWidget_3)
        self.s01.setObjectName("s01")
        self.gridLayout_3.addWidget(self.s01, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 2, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 4, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 3, 1, 1, 1)
        self.tabWidget.addTab(self.doityourself, "")
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog_rename_files)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 701, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_rename_info = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.button_rename_info.setObjectName("button_rename_info")
        self.horizontalLayout.addWidget(self.button_rename_info)
        self.LineEdit_rename_source_folder = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.LineEdit_rename_source_folder.setObjectName("LineEdit_rename_source_folder")
        self.horizontalLayout.addWidget(self.LineEdit_rename_source_folder)
        self.button_rename_browse = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.button_rename_browse.setObjectName("button_rename_browse")
        self.horizontalLayout.addWidget(self.button_rename_browse)
        self.label_19 = QtGui.QLabel(Dialog_rename_files)
        self.label_19.setGeometry(QtCore.QRect(10, 60, 241, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")

        self.retranslateUi(Dialog_rename_files)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("accepted()"), Dialog_rename_files.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL("rejected()"), Dialog_rename_files.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog_rename_files)
        Dialog_rename_files.setTabOrder(self.buttonBox, self.tabWidget)
        Dialog_rename_files.setTabOrder(self.tabWidget, self.button_rename_info)
        Dialog_rename_files.setTabOrder(self.button_rename_info, self.LineEdit_rename_source_folder)
        Dialog_rename_files.setTabOrder(self.LineEdit_rename_source_folder, self.button_rename_browse)
        Dialog_rename_files.setTabOrder(self.button_rename_browse, self.radioButton_prefix_datetime)
        Dialog_rename_files.setTabOrder(self.radioButton_prefix_datetime, self.comboBox_prefix_datetime)
        Dialog_rename_files.setTabOrder(self.comboBox_prefix_datetime, self.radioButton_prefix_date)
        Dialog_rename_files.setTabOrder(self.radioButton_prefix_date, self.comboBox_prefix_date)
        Dialog_rename_files.setTabOrder(self.comboBox_prefix_date, self.radioButton_prefix_string)
        Dialog_rename_files.setTabOrder(self.radioButton_prefix_string, self.prefix_string)
        Dialog_rename_files.setTabOrder(self.prefix_string, self.radioButton_suffix_donotuse)
        Dialog_rename_files.setTabOrder(self.radioButton_suffix_donotuse, self.radioButton_suffix_string)
        Dialog_rename_files.setTabOrder(self.radioButton_suffix_string, self.suffix_string)
        Dialog_rename_files.setTabOrder(self.suffix_string, self.radioButton_suffix_datetime)
        Dialog_rename_files.setTabOrder(self.radioButton_suffix_datetime, self.comboBox_suffix_datetime)
        Dialog_rename_files.setTabOrder(self.comboBox_suffix_datetime, self.radioButton_suffix_date)
        Dialog_rename_files.setTabOrder(self.radioButton_suffix_date, self.comboBox_suffix_date)
        Dialog_rename_files.setTabOrder(self.comboBox_suffix_date, self.radioButton_model)
        Dialog_rename_files.setTabOrder(self.radioButton_model, self.radioButton_orgfilename)
        Dialog_rename_files.setTabOrder(self.radioButton_orgfilename, self.comboBox_digits)
        Dialog_rename_files.setTabOrder(self.comboBox_digits, self.comboBox_startcount)
        Dialog_rename_files.setTabOrder(self.comboBox_startcount, self.radioButton_fileext_asis)
        Dialog_rename_files.setTabOrder(self.radioButton_fileext_asis, self.radioButton_fileext_tolower)
        Dialog_rename_files.setTabOrder(self.radioButton_fileext_tolower, self.radioButton_fileext_toupper)
        Dialog_rename_files.setTabOrder(self.radioButton_fileext_toupper, self.s01)

    def retranslateUi(self, Dialog_rename_files):
        Dialog_rename_files.setWindowTitle(QtGui.QApplication.translate("Dialog_rename_files", "Rename photos", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog_rename_files", "If alphabetical or date order matters in case you want to autonumber your images, then make sure that you load your images in the right order. This is not a problem for the Source folder here but can be a problem if you use a set of images from the Main screen.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog_rename_files", "Name:  Prefix_Suffix.extension", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog_rename_files", "File extension:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fileext_asis.setText(QtGui.QApplication.translate("Dialog_rename_files", "Leave as is", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fileext_tolower.setText(QtGui.QApplication.translate("Dialog_rename_files", "Make lowercase", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_fileext_toupper.setText(QtGui.QApplication.translate("Dialog_rename_files", "Make uppercase", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog_rename_files", "Select rename options:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog_rename_files", "In case your chosen options lead to duplicate names, the tool will automatically autonumber the images.\n"
"Please specify how the tool should do this.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Dialog_rename_files", "No. of digits", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_digits.setItemText(0, QtGui.QApplication.translate("Dialog_rename_files", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_digits.setItemText(1, QtGui.QApplication.translate("Dialog_rename_files", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_digits.setItemText(2, QtGui.QApplication.translate("Dialog_rename_files", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_digits.setItemText(3, QtGui.QApplication.translate("Dialog_rename_files", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_digits.setItemText(4, QtGui.QApplication.translate("Dialog_rename_files", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_startcount.setToolTip(QtGui.QApplication.translate("Dialog_rename_files", "When counting from the 1st image, the counting runs from 1 to n, like 01, 02, 03, etc.  When starting on the second image the counting runs from 00, 01, 02, etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_startcount.setItemText(0, QtGui.QApplication.translate("Dialog_rename_files", "Start counting on 1st image", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_startcount.setItemText(1, QtGui.QApplication.translate("Dialog_rename_files", "Start counting on 2nd image", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_suffix_datetime.setText(QtGui.QApplication.translate("Dialog_rename_files", "Date_time", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog_rename_files", "Suffix:", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_suffix_string.setText(QtGui.QApplication.translate("Dialog_rename_files", "String", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_datetime.setItemText(0, QtGui.QApplication.translate("Dialog_rename_files", "YYYYMMDDHHMMSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_datetime.setItemText(1, QtGui.QApplication.translate("Dialog_rename_files", "YYYYMMDD_HHMMSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_datetime.setItemText(2, QtGui.QApplication.translate("Dialog_rename_files", "YYYMMDD-HHMMSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_datetime.setItemText(3, QtGui.QApplication.translate("Dialog_rename_files", "YYYY_MM_DD_HH_MM_SS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_datetime.setItemText(4, QtGui.QApplication.translate("Dialog_rename_files", "YYYY-MM-DD-HH-MM-SS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_date.setItemText(0, QtGui.QApplication.translate("Dialog_rename_files", "YYYYMMDD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_date.setItemText(1, QtGui.QApplication.translate("Dialog_rename_files", "YYYY_MM_DD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_suffix_date.setItemText(2, QtGui.QApplication.translate("Dialog_rename_files", "YYYY-MM-DD", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_suffix_date.setText(QtGui.QApplication.translate("Dialog_rename_files", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_suffix_donotuse.setText(QtGui.QApplication.translate("Dialog_rename_files", "Do not use", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_model.setText(QtGui.QApplication.translate("Dialog_rename_files", "Camera model", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog_rename_files", "${Exif:Model}", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_orgfilename.setText(QtGui.QApplication.translate("Dialog_rename_files", "Original filename", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog_rename_files", "${filename}", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog_rename_files", "Prefix:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_date.setItemText(0, QtGui.QApplication.translate("Dialog_rename_files", "YYYYMMDD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_date.setItemText(1, QtGui.QApplication.translate("Dialog_rename_files", "YYYY_MM_DD", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_date.setItemText(2, QtGui.QApplication.translate("Dialog_rename_files", "YYYY-MM-DD", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_prefix_datetime.setText(QtGui.QApplication.translate("Dialog_rename_files", "Date_time", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_prefix_date.setText(QtGui.QApplication.translate("Dialog_rename_files", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_datetime.setItemText(0, QtGui.QApplication.translate("Dialog_rename_files", "YYYYMMDDHHMMSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_datetime.setItemText(1, QtGui.QApplication.translate("Dialog_rename_files", "YYYYMMDD_HHMMSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_datetime.setItemText(2, QtGui.QApplication.translate("Dialog_rename_files", "YYYMMDD-HHMMSS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_datetime.setItemText(3, QtGui.QApplication.translate("Dialog_rename_files", "YYYY_MM_DD_HH_MM_SS", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_prefix_datetime.setItemText(4, QtGui.QApplication.translate("Dialog_rename_files", "YYYY-MM-DD-HH-MM-SS", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_prefix_string.setText(QtGui.QApplication.translate("Dialog_rename_files", "String", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Dialog_rename_files", "Note: Some combinations of prefix and suffix are not allowed. Upon selection of the prefix, only the allowed suffixes are enabled.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.simple), QtGui.QApplication.translate("Dialog_rename_files", "Simple", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Dialog_rename_files", "d04 : date_time (YYYY_MM_DD_HH_MM_SS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog_rename_files", "d01 : date_time (YYYYMMDDHHMMSS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Dialog_rename_files", "d07 : date (YYYY_MM_DD)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Dialog_rename_files", "d05 : date_time (YYYY-MM-DD-HH-MM-SS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Dialog_rename_files", "d06 : date (YYYYMMDD)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog_rename_files", "d03 : date_time (YYYYMMDD-HHMMS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog_rename_files", "do2 : date_time (YYYYMMDD_HHMMSS)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Dialog_rename_files", "d08 : date (YYYY-MM-DD)", None, QtGui.QApplication.UnicodeUTF8))
        self.s01.setToolTip(QtGui.QApplication.translate("Dialog_rename_files", "You can use this string only in combination with one of the other options", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("Dialog_rename_files", "s02 : Camera model (${Exif:Model})", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Dialog_rename_files", "s03 : Original filename (${filename})", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Dialog_rename_files", "s05 : Iso value (${iso})", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Dialog_rename_files", "s04 : Author (${author})", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.doityourself), QtGui.QApplication.translate("Dialog_rename_files", "Do it yourself", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rename_info.setText(QtGui.QApplication.translate("Dialog_rename_files", "Info", None, QtGui.QApplication.UnicodeUTF8))
        self.LineEdit_rename_source_folder.setToolTip(QtGui.QApplication.translate("Dialog_rename_files", "If you select a source folder all images in that folder will be renamed. Note that also images in subfolders will be renamed.", None, QtGui.QApplication.UnicodeUTF8))
        self.button_rename_browse.setText(QtGui.QApplication.translate("Dialog_rename_files", "Browse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Dialog_rename_files", "Source folder:", None, QtGui.QApplication.UnicodeUTF8))

